# Generated by Django 6.0.4 on 2026-04-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
                ('temporada', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('genero', models.CharField(max_length=200)),
                ('episodios', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
