# Generated by Django 6.0.4 on 2026-04-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.URLField(blank=True, null=True)),
                ('fondo_perfil', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('genero_favorito', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_no_recomendado', models.CharField(blank=True, max_length=100, null=True)),
                ('anime_favorito', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
