# Generated by Django 6.0.4 on 2026-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fondo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fondos/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/'),
        ),
    ]
