# Generated by Django 6.0.4 on 2026-05-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_likeresena'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='proximo_episodio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
