# Generated by Django 6.0.4 on 2026-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_anime_fecha_emision_anime_proximo_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='estado_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='estado_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genero_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genero_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='titulo_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='titulo_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
