# Generated by Django 6.0.4 on 2026-05-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSilenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silenciador', to=settings.AUTH_USER_MODEL)),
                ('usuario_silenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silenciado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'usuario_silenciado')},
            },
        ),
    ]
