# Generated by Django 6.0.4 on 2026-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
