# Generated by Django 6.0.4 on 2026-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_anime_mal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
