# Generated by Django 6.0.4 on 2026-05-05 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_alter_anime_episodios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-anio', 'titulo'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AddField(
            model_name='anime',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='popularidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='titulo_ingles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='titulo_japones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='url_mal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='estado',
            field=models.CharField(choices=[('En emisión', 'En emisión'), ('Finalizado', 'Finalizado'), ('Próximamente', 'Próximamente'), ('Pausado', 'Pausado'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='estado_en',
            field=models.CharField(choices=[('En emisión', 'En emisión'), ('Finalizado', 'Finalizado'), ('Próximamente', 'Próximamente'), ('Pausado', 'Pausado'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='estado_es',
            field=models.CharField(choices=[('En emisión', 'En emisión'), ('Finalizado', 'Finalizado'), ('Próximamente', 'Próximamente'), ('Pausado', 'Pausado'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='temporada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
