# Generated by Django 6.0.4 on 2026-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_anime_options_anime_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
