# Generated by Django 6.0.4 on 2026-05-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_anime_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='contiene_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
