# Generated by Django 6.0.4 on 2026-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_resena_contiene_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='spoiler_reportes',
            field=models.IntegerField(default=0),
        ),
    ]
