# Generated by Django 6.0.4 on 2026-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_respuestaresena'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
