# Generated by Django 6.0.4 on 2026-05-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_perfilusuario_experiencia_perfilusuario_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('amistad', 'Solicitud de amistad'), ('strike', 'Strike'), ('sistema', 'Sistema'), ('like', 'Like'), ('respuesta', 'Respuesta'), ('nivel', 'Subida de nivel'), ('logro', 'Logro')], default='sistema', max_length=20),
        ),
    ]
