# Generated by Django 6.0.4 on 2026-05-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_alter_notificacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('viendo', 'Viendo'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('abandonado', 'Abandonado'), ('planeo_verlo', 'Planeo verlo')], default='planeo_verlo', max_length=20)),
                ('capitulos_vistos', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='catalogo.anime')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_anime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'unique_together': {('usuario', 'anime')},
            },
        ),
    ]
