# Generated by Django 6.0.4 on 2026-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_seguimientoanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoanime',
            name='motivo_abandono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
