# Generated by Django 6.0.4 on 2026-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_seguimientoanime_motivo_abandono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
