# Generated by Django 6.0.4 on 2026-05-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_mensajeglobalfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_nexus',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('vip', 'VIP'), ('helper', 'Helper'), ('mod', 'Moderador'), ('admin', 'Admin'), ('owner', 'Owner')], default='usuario', max_length=20),
        ),
    ]
